# -----
# 
# balance-options:
# 
# difficulty: (default 1) (range .1 - 10)
# the overall difficulty of this addon, affecting energy generation and consumption, item production, and recipe costs
# 
# mob-simulation-xp-chance: (default 2 (50%)) (range 1-10)
# amount of ticks average for a simulation chamber to output xp, higher number is lower change, at default its 1/2 or 50%
# 
# allow-sf-item-transform: (default false)
# Will allow the gear transformer to change slimefun gear's material. Diamond tools can already be upgraded to netherite, 
# but some addon developers do not want there gear to be transformable so change this at your own risk...
# 
# quarry-nether-materials-in-overworld: (default false)
# Allow quarries to mine quartz, netherite, netherrack in any world
# 
# -----
# 
# advanced-anvil-max-levels: 
# These are the maximum level of enchants that can be obtained by combining 2 of the same enchant of the same level.
# 
# -----
# 
# storage-unit-options: 
# display-signs: (default true)
# if true, signs connected to storage units will update wither the stored item and amount, this may increase timings
# 
# -----
# 
# infinity-enchant-levels:
# levels of infinity gear. this will not affect existing items. adding more enchants wont have any effect, only change levels. 
# KEEP IN MIND PROTECTION LEVELS PAST 10 ARE PURELY COSMETIC AND ARE THE SAME AS 5.
# 
# -----
balance-options:
  difficulty: 1.0
  allow-sf-item-transform: false
  quarry-nether-materials-in-overworld: false
storage-unit-options:
  display-signs: true
advanced-anvil-max-levels:
  sharpness: 9
  protection: 10
  fortune: 6
  efficiency: 7
  fire-aspect: 6
  power: 7
  thorns: 13
  looting: 6
  unbreaking: 13
infinity-enchant-levels:
  blade:
    sharpness: 20
    looting: 10
    fire-aspect: 10
  pickaxe:
    efficiency: 40
    fortune: 20
  shovel: 
    efficiency: 40
    silk-touch: 10
  axe:
    efficiency: 40
    sharpness: 20
    fire-aspect: 10
    looting: 0
    silk-touch: 0
  bow:
    power: 10
    flame: 10
    infinity: 10
    punch: 0
  crown:
    protection: 20
    aqua-affinity: 10
  chestplate:
    protection: 20
    thorns: 10
  leggings:
    protection: 20
    thorns: 10
  boots:
    protection: 20
    feather-falling: 0
    thorns: 0
  shield:
    protection: 20
    thorns: 10